name: MetaMask Security Code Scanner

on:
  workflow_call:
    secrets:
      SECURITY_SCAN_METRICS_TOKEN:
        required: false
      APPSEC_BOT_SLACK_WEBHOOK:
        required: false
  workflow_dispatch:

jobs:
  run-security-scan:
    name: Run Semgrep security scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Analyse code with Semgrep
        uses: MetaMask/Semgrep-action@main
        with:
          paths_ignored: |
            '**/jest.config.js'
            '**/jest.environment.js'
            '**/mocks/'
            '**/test/'
            'node_modules'
            'packages/delegator-e2e'
